{{- if and .Values.ingress.enabled .Values.ingress.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "gemx.fullname" . }}-mc
spec:
  domains:
  {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
  {{- end }}
{{- end }}
