# inventory/hosts.yml — inventário de hosts com tags/roles/grupos
groups:
  clinic:
    - clinic-vm
    - zt-db
  research:
    - lab-anon
hosts:
  clinic-vm:
    hostname: clinic-vm.ts.net
    user: ubuntu
    identity: "~/.ssh/id_ed25519"
    tags: [prod, clinic, db]
    roles: [db, api]
  zt-db:
    hostname: 10.147.20.33
    user: postgres
    identity: "~/.ssh/id_ed25519"
    tags: [prod, db, zerotier]
    roles: [db]
  lab-anon:
    hostname: 100.100.50.10
    user: research
    identity: "~/.ssh/id_ed25519_sk"
    tags: [research, tailscale]
    roles: [etl, viz]
